apiVersion: v1
kind: Service
metadata:
  labels:
    app: fabrikamfiber.web
  name: fabrikamfiberweb-craig
spec:
  ports:
  - port: 80
  type: "ClusterIP"
  selector:
    app: fabrikamfiber.web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fabrikamfiber-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - kubecon-demo-aks-ingress-craigp.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: kubecon-demo-aks-ingress-craigp.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /craig
        backend:
          serviceName: fabrikamfiberweb-craig
          servicePort: 80