apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fabrikamfiber-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - kubecon-demo-aks-ingress-craigp.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: fibrikamfiberweb.craig.svc.cluster.local
    http:
      paths:
      - path: /craig
        backend:
          serviceName: fabrikamfiberweb
          servicePort: 80